### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by marcelowu** [br-paypaldev/magento2-module#1]
funciona no pessoa fisica ?
erro na compilacao,
depois da instalacao aparece tbm erro  - We have identified that your store does not have an active phone, please enable to activate the module.

**Comment by apuhlmann** [comment]
Sim, exceto o PayPal Plus, todas as soluções funcionam para PF.
Quanto aos erros precisamos de imagens ou logs para entender o que acontece.

**Comment by marcelowu** [comment]
![capturar1](https://user-images.githubusercontent.com/30912144/39646936-7d6011ba-4fb3-11e8-8a5d-85b7a29e3c09.JPG)
![capturar2](https://user-images.githubusercontent.com/30912144/39646937-7d834590-4fb3-11e8-99e8-cf884b2878a4.JPG)

**Comment by apuhlmann** [comment]
Olá @marcelowu, 

Vamos analisar os logs e retornar com um feedback.

**Comment by katiakweb** [comment]
Estou exatamente com o mesmo erro... alguma solução?

**Comment by marcelowu** [comment]
Eu removir o pagseguro e deu certo

**Comment by katiakweb** [comment]
Pra mim esta solução não serve... preciso trabalhar com os dois gateways de pagamento, infelizmente tenho muitos clientes que preferem  o PagSeguro ainda... :-(

**Comment by apuhlmann** [comment]
@katiakweb @marcelowu 

Estamos tentando reproduzir o problema, o módulo do PagSeguro que estão utilizando é este? https://github.com/pagseguro/magento2

**Comment by marcelowu** [comment]
Isso

**Comment by marcelowu** [comment]
Talvez a versão do PHP e MySQL, atualize

**Comment by marcelowu** [comment]
Vc pode usar a versão do PagSeguro do bleez.

**Comment by katiakweb** [comment]
Sim, este mesmo!

**Comment by katiakweb** [comment]
Mas esta versão do PagSeguro do Bleez é para o Magento 2? É compatível com o Magento 2.1.9?

**Comment by marcelowu** [comment]
Sim, já testei

**Comment by marcelowu** [comment]
Mas, o SDK é antigo

**Comment by katiakweb** [comment]
Estou instalando aqui, vou testar e ver se funciona...

**Comment by katiakweb** [comment]
Bah, não vou poder testar, Sandbox do PagSeguro tá fora do ar... eu odeio este PagSeguro, pq as pessoas não se acostumam logo com o Paypal hein? Melhor serviço que existe, sem bajulação!

**Comment by marcelowu** [comment]
Problema eh boleto né, q PayPal não tem ainda
