### ISSUE TITLE
Incorrect API credentials in PayPal Plus

### ISSUE THREAD

**Issue by cfgalvani** [br-paypaldev/magento2-module#2]
Estou recebendo este erro ao tentar configurar o PayPal Plus em Sandbox. Já estamos habilitados para usar o PayPal Plus por inclusive usar em uma Loja Magento 1.9. Teria algo relacionado com a URL por ainda estar em ambiente de desenvolvimento? Ao talvez ao certificado SSL?

**Comment by apuhlmann** [comment]
Olá @cfgalvani, 

Primeiro, você está utilizando as mesmas credenciais de API de produção da sua loja 1.9 no sandbox do 2.0? Sandbox tem credenciais de API diferentes do ambiente de produção, este pode ser um problema.

Segundo, pode ter relação sim com certificados de segurança, ao tentar efetuar o handshake com o endpoint do PayPal a requisição é barrada e a comunicação não realizada.

Quais são os certificados do seu servidor?

**Comment by RubensSalles** [comment]
Olá.

Eu criei as credenciais api, juntamente com o suporte de vocês e tenho o mesmo erro, tanto para sandbox como produção. Meu magento é 2.2.4
