### ISSUE TITLE
Erro Magento 2.2.x

### ISSUE THREAD

**Issue by gutomissiatto-git** [br-paypaldev/magento2-module#3]
Ao informar as credencias o mesmo não salva as informações.
Verifiquei os Logs também não consta erro algum e/ou gera arquivo para identificação e correção.
- Testei via Sandbox e modo de produção e ocorre o mesmo problema.

**Comment by mscampos92** [comment]
mesmo problema aqui, ao clicar no botão salvar não acontece nada... alguma solução?

**Comment by gutomissiatto-git** [comment]
Solução é informar diretamente no DB ou downgrade para 2.2.5, porém acontece o bug de vez em quando..

**Comment by wagento-bhavin** [comment]
Same error. I filled up secret key and client id for sandbox account. It shows error "This is a required field." in this field even it is already filled up.
