### ISSUE TITLE
paypal plus erro

### ISSUE THREAD

**Issue by johnsonbio** [br-paypaldev/magento2-module#4]
o modulo nao reconhece ao selecionar o mesmo aparece a mensagem: Erro ao carregar o meio de pagamento. Tente novamente, se o problema persistir entre em contato.
Estou usando magento 2.2.5 com tema porto e o one step checkout (Aheadworks Extensions)

**Comment by ArmandoAAJ** [comment]
Estou com o mesmo, problema! Consegui resolver talvez? Versão Magento 2.2.4

**Comment by gutomissiatto-git** [comment]
Olá! Esse erro estava acontecendo comigo quando colocava um CPF inválido, após colocar um CPF válido a mensagem não é exibida e carrega normalmente o módulo.

Utilizo o Magento CE 2.2.5 e 2.2.6
