### ISSUE TITLE
Erro na execução do comando setup:di:compile 

### ISSUE THREAD

**Issue by renorram** [br-paypaldev/magento2-module#6]
Ao executar o setup:di:compile recebi os seguintes erros de compatibilidade com o core do Magento:
```
PHP Fatal error: Declaration of PayPalBR\PayPal\Block\Checkout\AttributeMerger::getDefaultValue($attributeCode) must be compatible with Magento\Checkout\Block\Checkout\AttributeMerger::getDefaultValue($attributeCode): ?string in /var/www/html/vendor/br-paypaldev/magento2-module/Block/Checkout/AttributeMerger.php on line 412
PHP Fatal error: Declaration of PayPalBR\PayPal\Block\Checkout\AttributeMerger::getCustomer() must be compatible with Magento\Checkout\Block\Checkout\AttributeMerger::getCustomer(): ?Magento\Customer\Api\Data\CustomerInterface in /var/www/html/vendor/br-paypaldev/magento2-module/Block/Checkout/AttributeMerger.php on line 412
```

Versão do Magento: 2.3.2

Acredito que sejam apenas incompatibilidades na declaração de metódos.

**Comment by gutomissiatto-git** [comment]
Olá @renorram, esta versão é compatível apenas com até 2.2.5. Consegui utilizar na 2.2.6 porem é necessário informar o DB as chaves API. Porém na 2.3.2 tiveram muitas mudanças e é bem possível  que tenha vários funções depreciadas. No seu ao salvar as chaves API, está normal? Tem horas que o botão não responde.
