### ISSUE TITLE
Módulo PayPal para Magento2 funciona para Magento 2.3 ?

### ISSUE THREAD

**Issue by yurimonteiro** [br-paypaldev/magento2-module#8]
Estou com a última versão do magento 2 versão 2.3, mas na descrição menciona que a compatibilidade é da versão 2.2.2 até 2.2.5, sabem me dizer se funcionará na versão 2.3?

**Comment by marcelo011982** [comment]
Nao funciona a  nao ser que haja algumas modificações, no PR tem uma delas.
https://github.com/br-paypaldev/magento2-module/pull/7#issue-322830187


A outra é em relação a proteção csrf que o  2.3 adota. Ricardo Martins colocou bem em:
https://www.magenteiro.com/blog/magento-2/desabilitar-csrf-no-controller/

Também há uma questa de versao do php que o modulo aceita ate 7,1. Caso seu servidor tenha mais que isso voce tera que retirar essa linha de la.

**Comment by mauricio-tonny** [comment]
Módulo atualizado para a versão 2.3 recomenda-se que tente instalar novamente, seguindo a instrução do README, caso retornar algum erro, inserir aqui na **Issue**
